OOP School Library: Set Up Associations
DJ-MrJay/oop-school-library pull request #3
Opened 2023-01-06 12:31 UTC by DJ-MrJay

In this milestone, I:
- Created a class <code>Classroom</code>
- Created the <code>has-many</code>/<code>belongs-to</code> relationship between <code>Classroom</code> and <code>Student</code> 
- Created a class <code>Book</code>
- Created a class <code>Rental</code>
- Created the <code>many-to-many</code> relationship between <code>Person</code> and <code>Book</code> using the intermediate class <code>Rental</code>

2023-01-06 17:07 UTC, uwadonat requested changes
## Hi @DJ-MrJay :hand: 

Good job so far! :mechanical_arm: 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
### Highlights
- Good pull request message ✔️
- Good commit history ✔️
- No linter errors ✔️
![almost](https://user-images.githubusercontent.com/65860678/211061412-37613051-2af4-49c0-a718-fafe531f7ce2.gif)
# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_- [ ] Please for your next pull request, consider to use the same link so that next reviewer can see how you implemented requested changes._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 17:07 UTC, uwadonat commented on person.rb
>    end
- [ ] `add_rentals` method should be present here.
`hint`:

def add_rental(book, date)
...

     end

2023-01-06 19:13 UTC, aimalamiri approved these changes
Hi @DJ-MrJay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ApprovedDavieGIF](https://user-images.githubusercontent.com/34779928/191333120-c0c2ce83-28e1-4dbc-aac1-09e467f7a8bd.gif)


## Highlights

- The associations between classes are setup properly ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 10:14 UTC, merged

2023-03-09 09:29 UTC, elisha2kyakpo1 reviewed
Hi 👋 @DJ-MrJay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

✔️ The PR title and description look good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._