OOP School Library: Add Basic UI
DJ-MrJay/oop-school-library pull request #4
Opened 2023-01-07 10:09 UTC by DJ-MrJay

- Created <code>app.rb</code> file to serve as console app entry-point
- Created <code>main.rb</code> to define the entry point with a method called <code>main</code> that is invoked at the end

2023-01-07 11:31 UTC, cynthiainga requested changes
Hi @DJ-MrJay, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 11:31 UTC, cynthiainga commented on person.rb
> +  def initialize(age, name = 'unknown', parent_permission: true)
- [ ] Good job so far but you still have some issues that need to be fixed. When I try to create a student the console app failed `wrong number of arguments`. Please kindly fix that 🙃 🙃 

<img width="1168" alt="Screen Shot 2023-01-07 at 14 16 31" src="https://user-images.githubusercontent.com/74501523/211147472-cf899944-e97b-4836-9cf3-fdef33d26dcc.png">

2023-01-07 11:31 UTC, cynthiainga commented on app.rb
> +    rental_item = Rental.new(date, book, person)
- [ ] Also when I try to create `rental` the console app failed, same error `wrong number of arguments`, kindly fix that as well 🙃 😉 

<img width="1168" alt="Screen Shot 2023-01-07 at 14 20 47" src="https://user-images.githubusercontent.com/74501523/211147609-4636ee8d-27d1-4184-bcb3-cf384fc35725.png">

2023-01-11 21:43 UTC, vickymarz approved these changes
Hi @DJ-MrJay, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the Git Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- App is working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 06:58 UTC, merged

2023-03-09 09:04 UTC, thecodechaser reviewed
## STATUS: APPROVED 🟢

## Hi @DJ-MrJay👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._